create component Game for hw-9
dontoouch/react-hw-tereh pull request #5
Opened 2022-04-23 16:11 UTC by dontoouch

2022-04-24 18:57 UTC, PaulVersAtile requested changes

2022-04-24 18:57 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +      borderRadius: "50%",
Постоянные стили лучше выносить в CSS

2022-04-24 18:57 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
Функция называется changeBg, что можно перевести как "поменять фон", хотя она просто генерит случайное число. Получается семантически неверное название

2022-04-24 18:57 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    const Circle = {
Переменные в js называются с маленькой буквы. С большой только компоненты

2022-04-24 18:57 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    const newY = getRandom(0,500);
Почему именно до 500? В задаче также сказано, что поле должно быть 1000х1000 px и зная радиус круга, можно точно вычислить границы для ГСЧ.

2022-04-24 18:57 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    <div className="conteiner">
Высота этого контейнера - 2px, а должна быть 1000

2022-04-24 21:01 UTC, dontoouch commented
Сделал коробку как и в условии , поправил все что нужно было . Хочу пояснить почему я использовал статичную величину для размеров круга(100) , а не вносил ее в переменную , а все это потому что , как только я так делал , неважно какими условиями я обкладывал код , но этот круг начинал мега странно себя вести , при каждом 2 клике прыгал за коробку , бывало и на 200 px , хотя в переменных были те же 100 px , и условия были такие же . Может я как-то неправильно эти переменные в хуки закидывал , хз , оставил пока что так

2022-04-27 08:43 UTC, PaulVersAtile commented
Когда появляется такое странное поведение, стоит его как-нибудь запечатлить, может быть записать видео и прикрепить к нему код, чтобы можно было посмотреть и обсудить, что в том коде верно, а что нет. Это был тот самый момент в который вполне можно было спросить и мы бы глянули что там не так. Если есть возможность откатить изменения и вернуться в то состояние - то можем глянуть

2022-04-28 14:09 UTC, PaulVersAtile requested changes

2022-04-28 14:09 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
Кружочек, к сожалению, всё равно периодически вылетает за рамки поля. Попробуй рассчитать какое максимальное значение можно задавать для позиции круга, учитывая размер поля и размер самого круга. И рандомить тогда не от 0 до 1000, а от 0 до этого рассчитанного значения

2022-04-28 14:09 UTC, PaulVersAtile commented on hw-9/src/Game.css
> + height: 100px;
В задаче радиус круга равен 100, значит ширина и высота контейнера должна быть 200 px :)

2022-04-28 14:15 UTC, dontoouch commented on hw-9/src/Game.js
> +    }
Так я понимаю , что я могу просто от 1000 отнять 200 и рандомить только в этом диапазоне , ну это как-то неприкольно , я бы предпочёл подход , которым я использовал, то есть рандом от 0 до 1000 и если это значение вылетает за границу , то тогда его обрабатывать .

2022-04-28 14:16 UTC, dontoouch commented on hw-9/src/Game.css
> + height: 100px;
Хахахаха , ой

2022-04-28 14:55 UTC, dontoouch commented
> <img alt="Снимок экрана 2022-04-28 в 19 05 04" width="975" src="https://user-images.githubusercontent.com/103578069/165771721-7d3318bb-f28f-4f2b-8869-249b763e4d20.png">

я забыл рассмотреть случай когда и по X и по Y генерится 1000 , исправил

2022-04-28 22:07 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
Ну так как нам точно известно в задаче, что диапазон для рандома получается от 0 до 800 - то грех этим не воспользоваться. Это нормальное решение в данном случае. Если бы верхняя граница была динамическая ( вдруг поле можно было бы ресайзить) - тогда уже да, какие-то доп. обработки имеет смысл добавлять. Но, в целом, ок, если интересно сделать так - то не вопрос. Единственное что выражение + 100 - 1000 - можно сократить до -900

2022-05-02 12:37 UTC, PaulVersAtile approved these changes

2022-05-02 12:37 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
На будущее - если есть возможность избежать таких конструкций - то лучше их избежать. Решение в две строки с рандомом от 0 до 800 выглядит проще, чище и понятнее. А такой код просто сложно читать и поддерживать в будущем. Всегда держи в голове что со всем что пишется сейчас будет вестись работа в будущем и возможно другими людьми. На этот раз аппрув, если интересно было повозиться, но на будущее  нужно писать максимально простое и читабельное решение исходя из условия задачи

2022-05-02 12:50 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
Посмотрел как работает код - кружочек слишком часто прилепляется к границам, видно что распределение неравномерное. Т.е. данный блок ифов работает когда мы получаем значение любой координаты от 800 до 1000 и нужную координату устанавливает в 800. Выходит что все значения от 800 до 1000 устанавливаются в 800, т.е. круг находится на границе поля. Если рандомить от 0 до 1000, то позиция круга не имеет одинаковую вероятность, при (0-800) и при (800-1000) она разная. Т.е. эти вычисления нарушают равную вероятность для всех позиций круга - он приклеивается к границе поля слишком часто, потому что целых 200 значений из 1000 преобразуются в 800. А такой случай должен быть только если выпало 800.

2022-05-02 12:52 UTC, PaulVersAtile requested changes

2022-05-02 12:52 UTC, PaulVersAtile commented on hw-9/src/Game.js
> +    }
Вот этот кусочек кода `newX-(newX+width-1000)` можно ж преобразовать к `1000-width` если раскрыть скобки

2022-05-07 10:56 UTC, merged