create component SayHi
dontoouch/react-hw-tereh pull request #7
Opened 2022-04-29 10:30 UTC by dontoouch

2022-04-29 10:34 UTC, dontoouch commented
хотел бы узнать почему кое-что не работает ( см. в коде)

2022-05-02 13:26 UTC, PaulVersAtile requested changes
В проекте в зависимостях нет typescript, поэтому не очень понятно, почему некоторые файлы имеют расширение tsx. У меня, например, проект не запускается

2022-05-07 10:55 UTC, dontoouch commented
закинул рабочий tsconfig , теперь у меня все работает

2022-05-10 14:16 UTC, PaulVersAtile requested changes

2022-05-10 14:16 UTC, PaulVersAtile commented on src/SayHi.tsx
> +  const [greeting , setGreeting] = useState<string>();
здесь надо в useState передать пустую строку, иначе TS думает что тип string | undefined, а с таким сложнее работать

2022-05-10 14:38 UTC, PaulVersAtile approved these changes

2022-05-10 15:25 UTC, merged