create component UserList hw-19
dontoouch/react-hw-tereh pull request #8
Opened 2022-04-30 07:15 UTC by dontoouch

2022-05-02 13:10 UTC, PaulVersAtile requested changes

2022-05-02 13:10 UTC, PaulVersAtile commented on src/UserList.css
> +.conteiner {
container. Много раз уже видел, всё же решил подсказать)

2022-05-02 13:10 UTC, PaulVersAtile commented on src/UserList.tsx
> +  console.log(data)
console.log над из финальной версии кода удалять

2022-05-02 13:15 UTC, dontoouch commented on src/UserList.tsx
> +  console.log(data)
А там в тз написано вывести в консоль :)

2022-05-04 15:37 UTC, PaulVersAtile commented on src/UserList.tsx
> +  console.log(data)
О, вопросов нет

2022-05-04 15:37 UTC, PaulVersAtile approved these changes

2022-05-07 11:08 UTC, merged